/* eslint-disable new-cap */
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { ReactQueryClientProvider } from "@/utils/react-query";
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="flex flex-col w-full items-center justify-center">
          <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
        </div>
      </body>
    </html>
  );
}
